export const wordList = [
  [["C", "O", "D", "E", "R"], "Someone who writes computer code"],
  [["S", "E", "R", "V", "E"], "Host or respond in networks"],
  [["R", "O", "U", "T", "E"], "Path for network traffic"],
  [["L", "O", "G", "I", "N"], "Sign into an account"],
  [["C", "A", "C", "H", "E"], "Stores quick data temporarily"],
  [["T", "O", "K", "E", "N"], "Authentication or data piece"],
  [["F", "I", "L", "E", "S"], "Stored documents on computer"],
  [["D", "R", "I", "V", "E"], "Stores files on a computer"],
  [["P", "A", "T", "C", "H"], "Fix a software problem"],
  [["Q", "U", "E", "U", "E"], "Lineup of tasks in code"],
  [["A", "R", "R", "A", "Y"], "List of items in programming"],
  [["C", "L", "I", "C", "K"], "Press a button on a mouse"],
  [["E", "M", "A", "I", "L"], "Electronic mail message"],
  [["I", "N", "P", "U", "T"], "Data entered into a computer"],
  [["M", "O", "U", "S", "E"], "Hand tool to move a cursor"],
  [["L", "A", "S", "E", "R"], "Used in optical mouse devices"],
  [["D", "E", "B", "U", "G"], "Find and fix errors"],
  [["L", "O", "G", "I", "C"], "Steps computers follow to decide"],
  [["P", "A", "R", "S", "E"], "Analyze code or data"],
  [["N", "O", "D", "E", "S"], "Points in a network"],
  [["S", "H", "E", "L", "L"], "Interface for typing commands"],
  [["M", "E", "R", "G", "E"], "Combine code or files"],
  [["M", "A", "C", "R", "O"], "Automate repetitive tasks"],
  [["A", "L", "E", "R", "T"], "Warning message in programs"],
  [["P", "R", "I", "N", "T"], "Output text on paper"],
  [["S", "T", "A", "C", "K"], "LIFO data structure in CS"],
  [["B", "Y", "T", "E", "S"], "Units of computer data"],
  [["P", "A", "N", "E", "L"], "Part of a user interface"],
  [["T", "H", "E", "M", "E"], "UI style or appearance"],
  [["S", "O", "U", "N", "D"], "Audio output from speakers"],
  [["L", "E", "V", "E", "L"], "Stage in a game"],
  [["F", "L", "O", "A", "T"], "Decimal number type in code"],
  [["S", "P", "A", "C", "E"], "Gap between words or objects"],
  [["R", "E", "S", "E", "T"], "Restart device or settings"],
  [["F", "I", "B", "E", "R"], "High speed internet line"],
  [["P", "O", "R", "T", "S"], "Connects devices to computer"],
  [["C", "R", "A", "S", "H"], "System stops working suddenly"],
  [["C", "O", "D", "E", "S"], "Instructions for a computer"],
  [["A", "B", "O", "R", "T"], "Cancel a running process"],
  [["T", "R", "A", "C", "E"], "Track code execution"],
  [["S", "T", "O", "P", "S"], "Halts a running program"],
  [["V", "A", "L", "U", "E"], "Data stored in variables"],
  [["B", "L", "O", "C", "K"], "Memory unit or blockchain part"],
  [["S", "A", "V", "E", "S"], "Preserve work on disk"],
  [["M", "O", "D", "E", "L"], "Representation in AI/ML"],
  [["C", "L", "O", "N", "E"], "Copy repository or code"],
  [["R", "E", "T", "R", "Y"], "Attempt the action again"],
  [["S", "H", "I", "F", "T"], "Keyboard key for capitals"],
  [["F", "E", "T", "C", "H"], "Get data from server"],
  [["P", "A", "S", "T", "E"], "Insert clipboard data"],
  [["I", "N", "D", "E", "X"], "Position in an array"],
  [["W", "H", "I", "L", "E"], "Loop type in code"],
  [["M", "E", "N", "U", "S"], "UI list of options"],
  [["T", "A", "B", "L", "E"], "Grid for data display"],
  [["E", "N", "T", "E", "R"], "Key to confirm action"],
  [["L", "I", "N", "K", "S"], "Connections between web pages"],
  [["P", "O", "I", "N", "T"], "Reference in memory or graphics"],
  [["R", "E", "P", "L", "Y"], "Respond to a message"],
  [["C", "H", "E", "C", "K"], "Verify or test a value"],
  [["T", "Y", "P", "E", "S"], "Data formats in code"],
  [["S", "C", "A", "N", "S"], "Search devices for threats"],
  [["P", "I", "X", "E", "L"], "Dot on the screen"],
  [["C", "O", "R", "E", "S"], "CPU processing units"],
  [["S", "T", "A", "R", "T"], "Begin process or application"],
  [["P", "A", "R", "T", "S"], "Hardware components"],
  [["A", "L", "I", "G", "N"], "Arrange elements neatly"],
  [["R", "O", "O", "T", "S"], "Admin user or base folder"],
  [["S", "Y", "N", "C", "S"], "Keep data updated"],
  [["Q", "U", "I", "T", "S"], "Close a program"],
  [["S", "E", "N", "D", "S"], "Transmit data"],
  [["F", "I", "N", "D", "S"], "Locate a file or string"],
  [["C", "L", "E", "A", "R"], "Erase data or screen"],
  [["R", "E", "P", "O", "S"], "Code storage spaces"],
  [["D", "A", "T", "A", "S"], "Information stored or used"],
  [["M", "E", "R", "G", "E"], "Combine code branches"],
  [["S", "T", "O", "R", "E"], "Keep data in memory"],
  [["O", "P", "E", "N", "S"], "Launch a file or app"],
  [["L", "O", "A", "D", "S"], "Bring data into memory"],
  [["S", "H", "A", "R", "E"], "Give access to others"],
  [["E", "X", "I", "T", "S"], "Leave a program"],
  [["M", "O", "D", "E", "S"], "Different program settings"],
  [["T", "A", "S", "K", "S"], "Jobs handled by CPU"],
  [["B", "O", "O", "T", "S"], "Start up system"],
  [["S", "T", "E", "P", "S"], "Sequence of actions"],
  [["F", "I", "X", "E", "S"], "Corrections in code"],
];
